Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.define "mail" do |b|
    b.vm.box = "debian/buster64"
    b.vm.hostname = "mail"
    b.vm.network "private_network", ip: "172.28.128.4"
    b.vm.provision "shell", path: "provision.sh", args: "mail"
  end

  config.vm.define "web" do |b|
    b.vm.box = "debian/buster64"
    b.vm.hostname = "web"
    b.vm.network "forwarded_port", guest: 80, host: 8080
    b.vm.network "private_network", ip: "172.28.128.3"
    b.vm.provision "shell", path: "provision.sh", args: "web"
  end
  
  config.vm.define "nfs" do |b|
    b.vm.box = "debian/buster64"
    b.vm.hostname = "nfs"
    b.vm.network "private_network", ip: "172.28.128.2"
    b.vm.provision "shell", path: "provision.sh", args: "zfs"
  end

  config.vm.define "rundeck", primary: true do |b|
    b.vm.box = "centos/7"
    b.vm.hostname = "rundeck"
    b.vm.network "forwarded_port", guest: 4440, host: 4440
    b.vm.network "private_network", ip: "172.28.128.5"
    b.vm.provision "shell", path: "provision.sh", args: "rundeck"
  end
end

# vim: ft=ruby syn=ruby fileencoding=utf-8 sw=2 ts=2 ai eol et si
