Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
  end

  config.vm.define "mail" do |b|
    b.vm.box = "debian/buster64"
    b.vm.hostname = "mail"
    b.vm.network "private_network", ip: "172.28.128.4"
  end

  config.vm.define "web" do |b|
    b.vm.box = "debian/buster64"
    b.vm.hostname = "web"
    b.vm.network "forwarded_port", guest: 80, host: 1234
    b.vm.network "private_network", ip: "172.28.128.3"
  end
  
  config.vm.define "zfs" do |b|
    b.vm.box = "debian/buster64"
    b.vm.hostname = "zfs"
    b.vm.network "private_network", ip: "172.28.128.2"
  end

  config.vm.define "rundeck", primary: true do |b|
    b.vm.box = "centos/7"
    b.vm.hostname = "rundeck"
    b.vm.network "forwarded_port", guest: 4440, host: 4440
    b.vm.network "private_network", ip: "172.28.128.5"
  end
end

# vim: ft=ruby syn=ruby fileencoding=utf-8 sw=2 ts=2 ai eol et si
